---
application:
  name: "botoftheorder"
  project: "bot-of-the-order"
  organization: "QoveryCommunity"
routers:
- name: "main-botoftheorder"
  routes:
  - application_name: "botoftheorder"
    paths:
    - "/*"
